name: Deploy WebAPI to Azure App Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-api:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.415'

      - name: Restore
        run: dotnet restore ZaposliMeWebAPI/ZaposliMe.WebAPI.csproj

      - name: Publish
        run: dotnet publish ZaposliMeWebAPI/ZaposliMe.WebAPI.csproj -c Release -o ${{ github.workspace }}\api-publish

      - name: Zip package
        shell: pwsh
        run: Compress-Archive -Path $Env:GITHUB_WORKSPACE\api-publish\* -DestinationPath $Env:GITHUB_WORKSPACE\api.zip -Force

      - name: Deploy to App Service (ZipDeploy)
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISH_PROFILE }}
          app-name: sljakomat-dgg5dhh6djbygkcf     # exact App Service name
          # slot-name: staging                    # <- uncomment if deploying to a slot
          package: ${{ github.workspace }}\api.zip
